workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - cd src && make

style-job:
  stage: test
  script:
    - cp materials/linters/.clang-format .
    - clang-format --Werror -n src/algorithms/*.cpp src/algorithms/*.hpp src/graph/*.cpp src/graph/*.hpp src/tests/*.cpp

unit_test-job:
  stage: test
  needs: [ build-job, style-job ]
  script:
    - cd src && make test